# Use plugins instead of require
plugins:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - "bin/**/*"
    - ".github/**/*"
    - "Rakefile"

# Style configurations
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 130

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

# RSpec configurations
RSpec/MultipleExpectations:
  Max: 10

RSpec/ExampleLength:
  Max: 30

# Performance configurations
Performance/StringReplacement:
  Enabled: true 
